#!/bin/bash

# Build script for creating embedded executables
# Usage: ./scripts/build-embedded.sh <project_dir> [output_name]

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <project_dir> [output_name]"
    echo "Example: $0 samples/kuma2 kuma2"
    exit 1
fi

PROJECT_DIR="$1"
OUTPUT_NAME="${2:-$(basename $PROJECT_DIR)}"

echo "Building embedded executable for: $PROJECT_DIR"
echo "Output name: $OUTPUT_NAME"

# Step 1: Copy project files to cmd/son-et/.embed directory
echo "Step 1: Preparing embedded files..."
EMBED_DIR="cmd/son-et/.embed"
rm -rf "$EMBED_DIR"
mkdir -p "$EMBED_DIR"
cp -r "$PROJECT_DIR"/* "$EMBED_DIR/"

# Step 2: Generate embedded_data.go file
echo "Step 2: Generating embedded_data.go..."
EMBED_DATA_FILE="cmd/son-et/embedded_data.go"

cat > "$EMBED_DATA_FILE" << EOF
//go:build !noembedded

package main

import "embed"

// Embedded project data
// This file is generated by scripts/build-embedded.sh
// Do not edit manually

//go:embed .embed/*
var embeddedFSData embed.FS

func init() {
	embeddedFS = embeddedFSData
	embeddedProject = ".embed"
}
EOF

echo "Generated $EMBED_DATA_FILE"

# Step 3: Build the executable
echo "Step 3: Building executable..."
go build -o "bin/$OUTPUT_NAME" ./cmd/son-et

# Step 4: Clean up
echo "Step 4: Cleaning up..."
rm -f "$EMBED_DATA_FILE"
rm -rf "$EMBED_DIR"

echo "Success! Embedded executable created: bin/$OUTPUT_NAME"
echo ""
echo "To run:"
echo "  ./bin/$OUTPUT_NAME"
echo ""
echo "To run in headless mode:"
echo "  ./bin/$OUTPUT_NAME --headless --timeout 5s"
